version: '3.9'
services:
  '0':
    build: ./roteador
    container_name: '0'
    environment:
      CONTAINER_NAME: '0'
      CUSTO_0_1_net: '8'
      CUSTO_0_2_net: '5'
    volumes:
    - ./roteador/roteador.py:/app/roteador.py
    networks:
      0_1_net:
        ipv4_address: 10.10.1.2
      0_2_net:
        ipv4_address: 10.10.2.2
    cap_add:
    - NET_ADMIN
  '1':
    build: ./roteador
    container_name: '1'
    environment:
      CONTAINER_NAME: '1'
      CUSTO_0_1_net: '8'
      CUSTO_1_4_net: '3'
      CUSTO_1_3_net: '8'
    volumes:
    - ./roteador/roteador.py:/app/roteador.py
    networks:
      0_1_net:
        ipv4_address: 10.10.1.3
      1_4_net:
        ipv4_address: 10.10.3.2
      1_3_net:
        ipv4_address: 10.10.4.2
    cap_add:
    - NET_ADMIN
  '2':
    build: ./roteador
    container_name: '2'
    environment:
      CONTAINER_NAME: '2'
      CUSTO_0_2_net: '5'
    volumes:
    - ./roteador/roteador.py:/app/roteador.py
    networks:
      0_2_net:
        ipv4_address: 10.10.2.3
    cap_add:
    - NET_ADMIN
  '3':
    build: ./roteador
    container_name: '3'
    environment:
      CONTAINER_NAME: '3'
      CUSTO_1_3_net: '8'
    volumes:
    - ./roteador/roteador.py:/app/roteador.py
    networks:
      1_3_net:
        ipv4_address: 10.10.4.3
    cap_add:
    - NET_ADMIN
  '4':
    build: ./roteador
    container_name: '4'
    environment:
      CONTAINER_NAME: '4'
      CUSTO_1_4_net: '3'
    volumes:
    - ./roteador/roteador.py:/app/roteador.py
    networks:
      1_4_net:
        ipv4_address: 10.10.3.3
    cap_add:
    - NET_ADMIN
  0_h1:
    build: ./host
    container_name: 0_h1
    networks:
      0_hosts_net:
        ipv4_address: 192.168.5.2
  0_h2:
    build: ./host
    container_name: 0_h2
    networks:
      0_hosts_net:
        ipv4_address: 192.168.5.3
  1_h1:
    build: ./host
    container_name: 1_h1
    networks:
      1_hosts_net:
        ipv4_address: 192.168.6.2
  1_h2:
    build: ./host
    container_name: 1_h2
    networks:
      1_hosts_net:
        ipv4_address: 192.168.6.3
  2_h1:
    build: ./host
    container_name: 2_h1
    networks:
      2_hosts_net:
        ipv4_address: 192.168.7.2
  2_h2:
    build: ./host
    container_name: 2_h2
    networks:
      2_hosts_net:
        ipv4_address: 192.168.7.3
  3_h1:
    build: ./host
    container_name: 3_h1
    networks:
      3_hosts_net:
        ipv4_address: 192.168.8.2
  3_h2:
    build: ./host
    container_name: 3_h2
    networks:
      3_hosts_net:
        ipv4_address: 192.168.8.3
  4_h1:
    build: ./host
    container_name: 4_h1
    networks:
      4_hosts_net:
        ipv4_address: 192.168.9.2
  4_h2:
    build: ./host
    container_name: 4_h2
    networks:
      4_hosts_net:
        ipv4_address: 192.168.9.3
networks:
  0_1_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.1.0/24
  0_2_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.2.0/24
  1_4_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.3.0/24
  1_3_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.10.4.0/24
  0_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.5.0/24
  1_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.6.0/24
  2_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.7.0/24
  3_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.8.0/24
  4_hosts_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.9.0/24
