FROM python:3.13.3-slim

RUN apt-get update && apt-get install -y \
  iproute2 \
  iputils-ping \
  net-tools \
  nano \
  tcpdump \
  traceroute \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY router.py .

ENV PYTHONUNBUFFERED=1

RUN pip install psutil

CMD ["python", "-u", "router.py"]
